server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: zh-picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password:
    username: root
    url: jdbc:mysql://localhost:3306/zh-picture
mybatis-plus:
  configuration:
    #mybatis 配置 驼峰 大小写
    map-underscore-to-camel-case: false
    #打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-not-delete-value: 0
      logic-delete-value: 1
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v1.0
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.zh.zhpicturebackend.controller
