server:
  port: 9000
  servlet:
    context-path: /api
spring:
  profiles: #本地使用local文件覆盖默认配置
    active: local
  application:
    name: zh-picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zh_picture
    password: 123456
    username: root
mybatis-plus:
  configuration:
    #mybatis 配置 驼峰 大小写
    map-underscore-to-camel-case: false
    #打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-not-delete-value: 0
      logic-delete-value: 1

